# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Movielandia' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Movielandia

  target 'MovielandiaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovielandiaUITests' do
    # Pods for testing
  end

  pod 'Firebase/Analytics', '~> 5.5'
  pod 'Firebase/Auth', '~> 5.5'
  pod 'Firebase/Database', '~> 5.5'

end
